# Generated by Django 5.0.6 on 2024-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0009_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='name',
        ),
    ]
